### ISSUE TITLE
Unable to drop items/view credits

### ISSUE THREAD

**Issue by AndrewHanes** [ComputerScienceHouse/WebDrink#5]
I'm unable to view credits.  It displays Andrew Hanes( credits) in the top right.  I am also unable to drop anything.  There is no message indicating what the error is, so I cannot really give much more detail, although I'm assuming that I'm not logged in correctly.

**Comment by seanmcgary** [comment]
Not really a bug as I had just taken the server down for some upgrades, but I added some visual alerts to the top of the page to show that the connection to drink has not been made.
