### ISSUE TITLE
Editing a different user sets your upper-right-hand balance to their balance

### ISSUE THREAD

**Issue by clockfort** [ComputerScienceHouse/WebDrink#6]
i.e. I have 900000000000000000 credits but if I subtract -135 credits from myself for a jolt drop and then -135 credits from will for a jolt drop (worr now has 479 credits after the subtraction), my displayed total number of credits in the top right is now incorrectly 479.

**Comment by seanmcgary** [comment]
Fixed in fda21199ec97130ec42c518a1d8da9365dad20c6
