### ISSUE TITLE
Drink Web Frontend is vulnerable to XSS through user-modifiable LDAP CN

### ISSUE THREAD

**Issue by clockfort** [ComputerScienceHouse/WebDrink#7]
i.e. I have bold and marquee tags in my CN, because I was testing to see if the sanitization function I wrote in my own webapp was working.

Guess whose name is bolded and flying across the screen right now on https://drink.csh.rit.edu.

:-P
Fix your shit, web-dev-noob.

It normally wouldn't be a problem fo realsies, if only I could see it, but I can make an admin see my CN by, say, asking them to enter my credits in, whereupon I can do crazy shit to them, open up a thousand goatse frames, push them a fake webauth login page, whatever the hell I want.

**Comment by seanmcgary** [comment]
Fixed. Now sanitizes uid field from LDAP.
