### ISSUE TITLE
Hitting enter breaks all the things

### ISSUE THREAD

**Issue by ryansb** [ComputerScienceHouse/WebDrink#8]
While editing counts in the machines interface, hitting enter after entering the number gives this error: 

Notice: Undefined offset: 0 in /var/www/priv/members/drink/core/bootstrap.php on line 103

Notice: Undefined offset: 1 in /var/www/priv/members/drink/core/bootstrap.php on line 104

Fatal error: Class name must be a valid object or a string in /var/www/priv/members/drink/core/loadFactory.php on line 35

**Comment by harlanhaskins** [comment]
Glad to see your issue has been fixed, @ryansb.
